#!/bin/bash

VARIABLE=VN1203
STRAIN="Mock NS1"
BASELINE=Mock
PERTURBATION=kegg_influenza_ns1
TIME="0h 3h 7h 12h 18h 24h"

for CONSTANT in $TIME
do
	INPUTDIR=ResultsCARNIVAL_${VARIABLE}vs${BASELINE}_for_${CONSTANT}r_${PERTURBATION}
	OUTPUTDIR=Results/${VARIABLE}vs${BASELINE}_for_${CONSTANT}r_${PERTURBATION}
	mv $INPUTDIR $OUTPUTDIR
done

